.TH MYCAT 1 "September 2025" "Version 0.4.1" "User Commands"
.SH NAME
mycat \- concatenate and display files
.SH SYNOPSIS
.B mycat
.RI [ options ] " file..."
.SH DESCRIPTION
The
.B mycat
utility reads files sequentially, writing them to the standard output.
With no FILE, or when FILE is -, read standard input.

This is a simplified version of the GNU cat command created as part of a project.
.SH AUTHOR
Your Name <maazhameed181@gmail.com>

